### ISSUE TITLE
Overwrites local .eslintrc.js config

### ISSUE THREAD

**Issue by AleksandrSl** [lamartire/sharec#123]
I have `.eslintrc.js` both in the config and in my project. sharec replaces local `.eslintrc.js` with file from the config. Is this expected behaviour?

**Comment by lamartire** [comment]
Hello! 
At this moment merge supports `json`, `yaml` and "lines based" files (like `.gitignore` or `.npmignore`), `js` and other extensions should be just replaced (this moment is described [here](https://github.com/lamartire/sharec/tree/master/packages/sharec#supported-configs)). It relates to impossibility to parse `js` file as file structure.
I can recommend you to use `.eslintrc`, or `.eslintrc.json`, `.eslintrc.yaml`. Sorry, but this is the only solution at this moment.

**Comment by AleksandrSl** [comment]
Thanks! What do you think about implementation difficulty? Is it feasible to be done in PR?

**Comment by lamartire** [comment]
Sure, PRs are always welcomed.
In the near future I'm planning to add codemods feature, potentially it can solve problem with similar cases which you described
