### ISSUE TITLE
Comments in JSON config

### ISSUE THREAD

**Issue by AleksandrSl** [lamartire/sharec#124]
In [ESLint](https://eslint.org/docs/user-guide/configuring#configuration-file-formats) documentation it's said that comments are allowed.
> JSON - use .eslintrc.json to define the configuration structure. ESLint's JSON files also allow JavaScript-style comments.

However `sharec` fails to apply them
```
sharec: × Configuration was not fully applyed due unexpected error
SyntaxError: Unexpected token / in JSON at position 868
```

**Comment by lamartire** [comment]
Hello again :)
`.eslint` supports comments in `json`, but potentially we can read json with comments, but can't save them after merge. It is due because sharec is processing all configs as data-structures.

**Comment by AleksandrSl** [comment]
Maybe it's worth adding to documentation? I can try to update README

**Comment by lamartire** [comment]
Yes, you can update root `README` and `README` in sharec package.

**Comment by lamartire** [comment]
@AleksandrSl `v2.3.0` will handle comments in `json` correctly
