### ISSUE TITLE
.sharecrc.json and sharec.configs inside package.json are ignored

### ISSUE THREAD

**Issue by derom** [lamartire/sharec#182]
I've tried to disable formatting using this config in <my-awesome-config>/package.json
`"sharec": {
    "configs": {
      "package.json": {
        "format": false
      }
    }
  }`
and this in <my-awesome-config>/.sharecrc.json
`{
    "configs": {
       "package.json": {
         "format": false
       }
    }
}`
Formatting was applied in both cases.
The issue seems to be caused by an unused file: https://github.com/lamartire/sharec/blob/9e24d08424938bdbde1bb2c9bc11b74ec3a9e869/packages/sharec/src/steps/readSharecConfig.js

**Comment by lamartire** [comment]
Probably it was solved in `2.8.1`, if not – feel free to reopen this issue, @derom.

**Comment by derom** [comment]
Still able to reproduce it in 2.8.1

**Comment by lamartire** [comment]
Fixed in `2.10.1`
