### ISSUE TITLE
merge strategy problem in package.json

### ISSUE THREAD

**Issue by AxeMea** [lamartire/sharec#185]
version: sharec@2.8.1

Hi

thanks for your great tool.

I found the merge strategy problem in package.json.

I just give an example for `eslintconfig` config. 

the same problem appear in others,like `postcss`,`babel` and so on.

```
// package.json in share-config package
{
...
"eslintConfig": {
  "root": true
}
...
}

// package.json in business project
{
...
"eslintConfig": {}
}
```

when update `share-config` package in business project, the `root` field dosen't merge into package.json in business project.

but if i use other custom prop like this:

```
// package.json in share-config package
{
...
"eslintConfig": {
  "customProp": true
}
...
}

// package.json in business project
{
...
"eslintConfig": {}
}
```

it's ok. 

i am not sure it is right or wrong for sharec?

**Comment by lamartire** [comment]
I think it's a sharec problem.
You said, that the problem appears also in `postcss`, `babel`. Which fileds have the problem? Only root?
Do you have anything in `node_modules/.cache/sharec`? If yes, did you have missed fields before?

**Comment by AxeMea** [comment]
@lamartire 

thanks your reply.

I know the reason that some version files in `node_modules/.cache`. 

I will close the issue.

😊

**Comment by lamartire** [comment]
Oh, ok! Anyway, If you face with any problem again – feel free to reopen issue or open new one
