### ISSUE TITLE
problematic command line

### ISSUE THREAD

**Issue by daiyam** [lamartire/sharec#216]
Hi,

I'm having an issue with the command `npx fixpack || true` in `package.json/scripts`.

I'm getting the error:
```
✖ Initializing sharec
TypeError: Cannot read property 'split' of undefined
    at /test/node_modules/sharec-schema/lib/helpers/commandsToMap.js:36:58
    at Array.reduce (<anonymous>)
    at commandsToMap (/test/node_modules/sharec-schema/lib/helpers/commandsToMap.js:22:30)
    at commandAtom (/test/node_modules/sharec-schema/lib/atoms/command.js:61:41)
    at /test/node_modules/sharec-schema/lib/actions/compose.js:46:9
    at /test/node_modules/sharec-schema/lib/actions/compose.js:83:65
    at /test/node_modules/sharec-schema/lib/actions/compose.js:46:9
    at Object.<anonymous> (/test/node_modules/sharec-schema/lib/actions/compose.js:82:69)
    at Object.processor (/test/node_modules/lodash/_createFlow.js:71:31)
    at /test/node_modules/sharec/src/steps/mergeConfigs.js:78:39
```

I've look at `commandsToMap`, it's splitting the command into subcommands and arguments. But why?

PS: I have to add `|| true` because `fixpack` in return 1 even when it has successfully fixed the `package.json`

**Comment by lamartire** [comment]
We should to process commands as data structures, where command is a key and arguments are members, but at the same time, we can have multiple members with the same key.
It needs for cases, when current state is `npx eslint && npx stylelint` and upcoming one is `npx eslint --fix && npx stylelint`. We should merge each command member correctly.
As I see here, we should handle this case in `commandsToMap` and thats would be enough to fix the problem.

**Comment by daiyam** [comment]
Are you working on that? Or can I make a PR to fix it?

**Comment by lamartire** [comment]
Thank you for your PR! :)
