### ISSUE TITLE
Invalid updating flow

### ISSUE THREAD

**Issue by ai** [lamartire/sharec#47]
I have a config with these scripts in `package.json`.

```js
  "scripts": {
    "api": "documentation build *.js -f md -o api.md",
    "spell": "yarn api && yaspeller-ci *.md",
    "clean": "rimraf api.md coverage/",
    "test": "jest --coverage && eslint-ci . && size-limit && yarn spell"
  },
```

I added this config to my project and changed `api` script:

```diff js
  "scripts": {
-   "api": "documentation build *.js -f md -o api.md",
+   "api": "documentation build *.js async/*.js -f md -o api.md",
    "spell": "yarn api && yaspeller-ci *.md",
    "clean": "rimraf api.md coverage/",
    "test": "jest --coverage && eslint-ci . && size-limit && yarn spell"
  },
```

When I updated the script, sharec clean my `api` script changes

**Comment by lamartire** [comment]
Thank you for issue! I think this problem directly relates to #46. I will fix both problems as soon as it possible.

**Comment by ai** [comment]
I checked the latest sharec and it repeats the problem.

You can repeat the problem by cloning [Nano ID], switching to [this commit](https://github.com/ai/nanoid/commit/21685b7cce439594677016e63879c86eb0ebebae) and then call `yarn upgrade-interactive --latest` with config update.

**Comment by lamartire** [comment]
So, I have switched to [this commit](https://github.com/ai/nanoid/tree/21685b7cce439594677016e63879c86eb0ebebae) and tried to update configuration:

```diff
 "scripts": {
-   "api": "documentation build *.js {async,non-secure}/*.js -f md -o api.md",
+   "api": "documentation build *.js -f md -o api.md",
    "spell": "yarn api && yaspeller-ci *.md",
    "clean": "rimraf api.md coverage/",
    "lint": "eslint-ci . --ignore-pattern 'node_modules' --ignore-pattern 'test/demo/build'",
-   "test": "jest --coverage && yarn lint && yarn spell",
+   "test": "jest --coverage && eslint-ci . && size-limit && yarn spell",
    "start": "parcel serve test/demo/index.html -d test/demo/build --open"
  }
```
Is it ok? I can advice you to use lastest release after publishing.
If it problem will be figure in again – feel free to reopen this issue.

**Comment by ai** [comment]
Does still sharec override my commands during the update? My point is that during config updating  if sharec see that  `package.json` already have the command with a different value, sharec should not change it.

Here is an example:

Sharec config version 1

```js
"scripts": {
  "a": 1,
  "b": 1
}
```

Sharec config version 2

```js
"scripts": {
  "a": 2,
  "b": 2
}
```

`package.json`:

```js
"scripts": {
  "a": 10,
  "b": 1
}
```

During the update from 1 to 2, the result should be:

```js
"scripts": {
  "a": 10,
- "b": 1
+ "b": 2
}
```

**Comment by lamartire** [comment]
@ai ah, I finally got it.
Yes, there is a big problem, because before update `sharec` removes previous installed configuration and applying next one.
So, I need some time to research possible ways to solve this problem.

**Comment by lamartire** [comment]
I think, we should backup previous applied configuration to the abstract lock-file because during update installing we have not access to previously installed configuration. I think it is not very difficult but it can really solve your problem.

**Comment by ai** [comment]
>  think, we should backup previous applied configuration to the abstract lock-file

Good idea, we can do it in `node_modules/.cache/sharec/CONFIG_NAME/VERSION`

**Comment by lamartire** [comment]
I think better idea to store it in the project root, because in your case – we lost this feature on repository level (`node_modules` commonly ignored).
And if we have look on the [new package managers](https://github.com/npm/tink) – `node_modules` will be rudimentary artifact in the near future, imo.

**Comment by lamartire** [comment]
Correct me if I'm wrong :)

**Comment by ai** [comment]
We are creating a tool to deal with less configs. Adding new config will be very bad for promotion.

In my experience JS developers against any new files in the root (I agree with them, extra file moves README below in the page and reduce promotion potential of my tools).

**Comment by lamartire** [comment]
Ok, I see.
It will be just restriction and users should accept it before use.

**Comment by ai** [comment]
It will drastically reduce benefits of the tool. A lot of users will refuse using library because of the extra file in the root.

Another way is to download previous version from mom directly.

**Comment by lamartire** [comment]
Yes, I absolutely agree with you!👌

**Comment by lamartire** [comment]
@ai finally – I have done that issue.
Eslint and other strategies were not affected in the last release but you can check issue with scripts.
I will make issues for other strategies.
