### ISSUE TITLE
Sharec change order of the package.json keys

### ISSUE THREAD

**Issue by ai** [lamartire/sharec#48]
```sh
git clone git@github.com:ai/nanoevents.git
yarn upgrade-interactive --latest
# Select @logux/sharec-config
git diff
```

Sharec will change `package.json`

```diff
   "yaspeller": {
     "lang": "en",
     "ignoreCapitalization": true,
-    "ignoreText": [
-      " \\(by [^)]+\\)."
-    ],
     "dictionary": [
       "EventEmitter",
       "gzipped",
@@ -92,9 +89,12 @@
       "npm",
       "unbindAll",
       "Versioning"
+    ],
+    "ignoreText": [
+      " \\(by [^)]+\\)."
     ]
   },
```

**Comment by lamartire** [comment]
Yea, I know this problem. So, I have some ideas how to solve this, but I would close other issue first :)

**Comment by ai** [comment]
Do you need help here? I can provide help via [Cult of Martians](https://cultofmartians.com/)

**Comment by lamartire** [comment]
@ai thank you, but not now. I had a very difficult time, now I'm on vacation and planning to solve all problems in the near time :)
I will certainly notify you.

**Comment by lamartire** [comment]
We can try to use `yaml` parser for `json`, or [json5](https://github.com/json5/json5), or [JSONC](https://github.com/tcorral/JSONC).

**Comment by ivasyutaalexey** [comment]
Hi, what about this issue? It would be really nice if sharec will merge keys in alphabetic order.

**Comment by lamartire** [comment]
Hello, @ivasyutaalexey! At this moment I have a lot of questions for core redesign and sorting of fields would be able some time later 🤷‍♀ 
I will notify you :)

**Comment by lamartire** [comment]
I have a good news! In the new version this problem was solved and should be released in the near time! :tada:
