### ISSUE TITLE
Sharec does not remove dependencies removed in config

### ISSUE THREAD

**Issue by ai** [lamartire/sharec#49]
In `@logux/sharec-config` 0.3.1 I removed `eslint-plugin-import-helpers` https://github.com/logux/sharec-config/commit/914085b135084baf69069bd1dada0957fd4278ca

When I update the config in [Nano ID](https://github.com/ai/nanoid/), Sharec doesn’t remove `eslint-plugin-import-helpers` from dependencies.

**Comment by lamartire** [comment]
@ai, sharec removes dependencies which have equal versions. Do your projects match to this point?
For example, if you have `0.1.0` in your config and `0.2.0` in project – dependency will not removed, because it potentially was changed by user for self purposes.

**Comment by ai** [comment]
> Do your projects match to this point?

Yeap https://github.com/ai/nanoid/blob/master/package.json#L40 https://github.com/logux/sharec-config/commit/914085b135084baf69069bd1dada0957fd4278ca
