### ISSUE TITLE
Merge eslintIgnore changes

### ISSUE THREAD

**Issue by ai** [lamartire/sharec#51]
[Nano ID](https://github.com/ai/nanoid/) has `eslintIgnore` keys in `package.json`:

```js
  "eslintIgnore": [
    "node_modules",
    "test/demo/build"
  ]
```

My sharec config has:

```js
  "eslintIgnore": [
    "node_modules",
    "test/demo/build"
  ]
```

Every time when I update the config, sharec remove `test/demo/build` from `package.json`.

**Comment by lamartire** [comment]
This case caused by sharec installaction flow.
Due to impossibility to detect upcoming configuration version sharec removes previous installed configs and then install upcoming configuration package.
`test/demo/build` removes after installation, right?

**Comment by ai** [comment]
It was remove during the update of `@logux/sharec-config` and `sharec`.

Nano ID already had `package.sharec` key.

**Comment by lamartire** [comment]
Aww, now I understand. I had thought about `eslint`, but this is issue about `eslintIgnore`.
That is not difficult, I will do that in a few time later.

**Comment by lamartire** [comment]
@ai finally, I did it. It was a not difficult issue, but it has wise me to improve some "thin" moments. Thank you! 🎉
