### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by ai** [lamartire/sharec#55]
I have [monorepo](https://github.com/ai/size-limit/tree/multi) with sharec in the root. When I call `npm install` on the root (it triggers `npm install` in each package) I got unnecessary sharec changes in packages.

**Comment by lamartire** [comment]
@ai which packages were affected by sharec? Does it reproduces with calling `yarn` or `npm i` in the root of project?

**Comment by ai** [comment]
https://github.com/lamartire/sharec/issues/47

**Comment by lamartire** [comment]
@ai please, check, does it actual?

**Comment by ai** [comment]
The problem was not reproduced on `size-limit` with new Sharec

**Comment by lamartire** [comment]
Very cool news! 🎉
