### ISSUE TITLE
Can we have overrides?

### ISSUE THREAD

**Issue by pirix-gh** [lamartire/sharec#58]
Hi @lamartire, first of all bravo for this package. I also had the idea to simplify the build/setup process, but I couldn't have done it simpler than this. You had a very good idea, congrats :clap: !

I have a few more questions, before I set this up on my projects:
- Is there a way to override the configuration files that will be installed?
- Are all the configuration files supported, is it generic?

Once again, this is really cool. It replaces the need (for me) to setup lerna for my projects, it's minimalistic, waaay simpler and lightweight.

**Comment by lamartire** [comment]
Hello, @pirix-gh! Thank you for your reply, it's very important for me :)
So, now I working on the new core logic, you can read thoughts about in #47. It should solve problem with some issues related to invalid merging. But as regards files overriding – no, sharec does not do that on the current state. It is not very difficult imo and we can do that with additional option for `install` command. For example: `sharec install` – will merge and copy files, but `sharec install -f` – override existing files without merge. What do you think?
Now, `sharec` supports all `.json` and `.yml` files, but for some tool it has special strategies, among them: `eslint`, `babel`, `yaspeller`. It the first future (of course after logic redesign 😉) I want to implement #57 and #56.
You can propose config what you need in issues.
Have a nice day! 🙌

**Comment by lamartire** [comment]
Hey, @pirix-gh! Overwrite mode was implemented by me in commits below.
It should be available in the next release 😉
