### ISSUE TITLE
Publish .npmignore to sharec package

### ISSUE THREAD

**Issue by ai** [lamartire/sharec#60]
I have share config with:

```
configs/
  .travis.yml
  .npmignore
```

`configs/.npmignore` contains `.travis.yml`. As a result, I can’t put `.travis.yml` to sharec config package.

Let’s add alias for `.npmignore` (for instance `npmignore`) and sharec will rename config during `postinstall`.

**Comment by lamartire** [comment]
It is not big problem. I think we should have abstract hooks in strategies for better and flexible work with files.
I will do that after #47.
Good issue, thank you!

**Comment by lamartire** [comment]
Hello, @ai! I have just implemented aliasing feature.
Now it relates only to `.npmignore` and case that was described by you.
I will ship it in the next release.

**Comment by ai** [comment]
So I should have `configs/npmignore` in my sharec config and sharec will transform it to `.npmignore`?

**Comment by lamartire** [comment]
> So I should have `configs/npmignore` in my sharec config and sharec will transform it to `.npmignore`?

Yes. Alias in strategy now forces output name. For example:

```js
const npmIgnoreStrategy = new NPMIgnoreStrategy({
  matchers: {
    lines: ['.npmignore', 'npmignore'],
  },
  alias: '.npmignore',
})
```

`npmignore` will be always transformed to `.npmignore`. But I think alias is not a good name for that feature.
