### ISSUE TITLE
Does not update devDependencies

### ISSUE THREAD

**Issue by ai** [lamartire/sharec#72]
1. I [added a new dependency](https://github.com/logux/sharec-config/commit/ff6eda8b674e6beb08a8f9d68d6ed56563201c80#diff-968ff7615d4c364a732075a8b424a49aR24) to my config 
2. `git clone https://github.com/ai/nanoid.git`
3. `yarn`
4. `yarn upgrade-interactive --latest`, select `@logux/sharec-config`
5. **`eslint-plugin-unicorn` was not added to `devDependencies`**

**Comment by lamartire** [comment]
Hey @ai! Thank you for issue!
I will fix it in a few days.

**Comment by lamartire** [comment]
@ai, try to remove [this line](https://github.com/logux/sharec-config/blob/master/package.json#L12).
I've describe that problem in latest releases and documentation – `remove` command in npm-script can produce a lot of unexpected problems.
Install command now includes logic for previous configuration removing.

**Comment by lamartire** [comment]
This breaking change has appeared in [v2.10.0-beta](https://github.com/lamartire/sharec/releases/tag/v2.10.0-beta) release.

**Comment by lamartire** [comment]
If it will not help for you, please, write me up :)

**Comment by ai** [comment]
I [removed script](https://github.com/logux/sharec-config/commit/62bfa0fa82c6b8b342515fa73b9d8b4e2d8aa6c8) but error still exists

**Comment by lamartire** [comment]
Thank you, I will try to reproduce that.

**Comment by lamartire** [comment]
Oh, I have an idea! May be problem with config package name, it includes slashes. May it is issue with caching.
I will add errors printing and verbose mode for easily error catching.

**Comment by hacknug** [comment]
Not sure it's the same error I experienced but when trying to update with `yarn upgrade-interactive`, everything coming from my config was removed from `package.json`. Manually changing the version of my config package and running `yarn install` brought everything back. Name of my package also contains a slash (`@hacknug/gridsome-config`).

**Comment by lamartire** [comment]
@hacknug that is very important information! Thank you :)
I'm ill now, but I will try to solve that issue on the next weekend.

**Comment by hacknug** [comment]
No problem. Let me know if I can help with testing or anything else 👍

**Comment by lamartire** [comment]
Guys, it was stupidly simple error. I have add some logic for sharec installation to configuration packages, but core module had not any tests and it is was the greatest failure! Just one logic negation operator!
I will publish new release, please – try to use updated version. I hope that problem was finally solved.
