### ISSUE TITLE
New Share doesn’t work correctly

### ISSUE THREAD

**Issue by ai** [lamartire/sharec#75]
1. `git clone https://github.com/ai/nanoevents.git`
2. cd `nanoevents`
3. `yarn`
4. `yarn upgrade-interactive --latest` and select `@logux/sharec-config`
5. Sharec removed `.travis,yml` and `.gitignore`
6. Sharec doesn’t add dependencies from config like `eslint-plugin-unicorn`

**Comment by lamartire** [comment]
There were some changes for `sharec` meta-data in `package.json`. 
Try to remove `sharec` property and then run `yarn upgrade-interactive`.
I guess it can help you.

**Comment by ai** [comment]
Can you try in `nanoevents` repository to be sure that it is a solution?

**Comment by lamartire** [comment]
Yes, I have check that case. There is part of git diff after update:

![image](https://user-images.githubusercontent.com/13414205/66292725-a08d0380-e8ed-11e9-8b30-289d0791d3fa.png)

**Comment by lamartire** [comment]
And `git status` log:

![image](https://user-images.githubusercontent.com/13414205/66292801-d8944680-e8ed-11e9-8383-dde9b21b182a.png)

**Comment by lamartire** [comment]
`eslint-plugin-unicorn` was added and other files were just modified.

**Comment by lamartire** [comment]
May be, it was problem with cache. I will try to test it a little later.

**Comment by ai** [comment]
> May be, it was problem with cache. I will try to test it a little later.

```sh
yarn cache clean
yarn upgrade-interactive --latest
```

doesn’t work too.

> Try to remove sharec property and then run yarn upgrade-interactive.

I tried and it helped. But now I have another problem. New lines was removed from `.gitignore` (but I have them in config).

**Comment by lamartire** [comment]
No, I mean `sharec` cache and I almost sure – problem in it.

**Comment by lamartire** [comment]
Problem with `.gitignore` and `.npmignore` still actual.

**Comment by lamartire** [comment]
Hope it was fixed in `2.14.0-beta`.

**Comment by dmitryshelomanov** [comment]
@lamartire yml problem still actual

**Comment by lamartire** [comment]
@dmitryshelomanov which `yaml` files you need to merge? Can you share repository?
