### ISSUE TITLE
Not work on Windows

### ISSUE THREAD

**Issue by Airkro** [lamartire/sharec#81]
version: v2.x

**Comment by lamartire** [comment]
Hello, @Airkro! Thank you, will look your problem as soon as it possible.

**Comment by lamartire** [comment]
@Airkro, can you give me a link with your config?
Which version of windows you are using?

**Comment by lamartire** [comment]
So, there was really problem with windows. I'm very sorry for that.
Next release will be on this week, I will notify you, @Airkro!

**Comment by lamartire** [comment]
@Airkro, I have released new version `2.14.0-beta`. Please, if it will not help you – reopen this issue or create new one.

**Comment by grom194** [comment]
still not work

**Comment by lamartire** [comment]
@grom194 can you provide any additional info? I have tested it on Windows 10 and node 10.

**Comment by grom194** [comment]
> @grom194 can you provide any additional info? I have tested it on Windows 10 and node 10.

windows 10 1607, node 12.13.0


```
C:\projects\work\common>npm i sharec-demo-config

> sharec-demo-config@2.14.0-beta postinstall C:\projects\work\common\node_modules\sharec-demo-config
> sharec install

npm WARN The package webpack is included as both a dev and production dependency.
npm WARN The package webpack-cli is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ sharec-demo-config@2.14.0-beta
added 1 package from 1 contributor, removed 2 packages and audited 1023070 packages in 60.718s
found 9 vulnerabilities (2 low, 2 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by lamartire** [comment]
Very interesting. Will check it sometimes later.

**Comment by lamartire** [comment]
@Airkro hey! I've reproduced that. Now I have laptop with dualboot and windows and I'll fix that on this week.

**Comment by lamartire** [comment]
Hey @Airkro, @bkoshelev - try new version `2.0.0-rc.0` it is just support windows.
Sorry, that it release took a lot of time, but it includes very important things beside windows support.
Have a nice day!
